create table public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null check (category in ('Indian Weddings', 'Parties', 'Baby Showers', 'Pre-Weddings', 'Travel')),
  year text not null,
  image_url text not null,
  size text not null default 'wide' check (size in ('wide', 'tall', 'square')),
  created_at timestamptz not null default now()
);

alter table public.gallery_items enable row level security;

create policy "Published gallery is public"
on public.gallery_items for select
using (true);

create policy "Authenticated users can publish gallery"
on public.gallery_items for insert
to authenticated
with check (true);

insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do nothing;

create policy "Portfolio images are public"
on storage.objects for select
using (bucket_id = 'portfolio');

create policy "Authenticated users can upload portfolio images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'portfolio');

create policy "Authenticated users can delete portfolio images"
on storage.objects for delete
to authenticated
using (bucket_id = 'portfolio');
